server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-catalog
          uri: lb://api-catalog
          predicates:
            - Path=/catalog/**
        - id: api-movie
          uri: lb://api-movie
          predicates:
            - Path=/movies/**
        - id: api-serie
          uri: lb://api-serie
          predicates:
            - Path=/serie/**

info: 
  app: 
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true 
  endpoints:
    web:
      exposure:
        include: gateway
